name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        runs-on: [self-ubuntu-24.04, karolina]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create sif filename
        run: |
          sif=$(basename "${{ github.repository }}.sif")
          echo "SIF_FILENAME=$sif" >> $GITHUB_ENV

      - name: PULL Apptainer SIF
        run: |
          if [ "${{ matrix.runs-on }}" == "karolina" ]; then
            module load apptainer/1.2.5
            apptainer_cmd=$(command -v apptainer)
          else 
            apptainer_cmd=/opt/apptainer/v1.4.0/apptainer/bin/apptainer
          fi  
          echo "Using apptainer command: $apptainer_cmd"
          # Save the command in the environment for subsequent steps
          echo "APPTAINER_CMD=$apptainer_cmd" >> $GITHUB_ENV
          # Pull the SIF file from GHCR
          $apptainer_cmd pull -F $SIF_FILENAME oras://ghcr.io/${{ github.repository }}:solution-sif
          $apptainer_cmd inspect $SIF_FILENAME

      - name: Run Container
        if: matrix.runs-on == 'self-ubuntu-24.04'
        run: |
          # Run the SIF using the stored APPTAINER_CMD command and mpirun
          mpirun -np 4 $APPTAINER_CMD run $SIF_FILENAME myapp

      - name: Run Container
        if: matrix.runs-on == 'karolina'
        run: |
          bash job_monitor.sh $SIF_FILENAME
